dynamic:
  datasource:
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xx.xx.xx.xx:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&rewriteBatchedStatements=true
      username: xx
      password: xx
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xx.x.x.x:3306/xx?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&rewriteBatchedStatements=true
      username: xx
      password: xx
      filters: stat,wall,slf4j
    framework:
      #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #url: jdbc:p6spy:mysql://xxx.xx.xx.xx:3306/aaaaa?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xx.xx.xx.xx:3306/xx?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
      username: aaaa
      password: aaaaa
      filters: stat,wall,slf4j