rabbit:
  publisherConfirmType: SIMPLE
  publisherReturns: true
  addresses: 192.168.1.245:5672,192.168.56.101:5672
  username: britton
  password: britton
  virtualHost: /
  cacheMode: CHANNEL
  canalQueue: canalQueue
  defaultQueueName: geoxus
  template:
    mandatory: true