web-mvc:
  platform:
    admin:
      beanName: GXMyAuthorizationInterceptor
      urlPatterns:
        - /**/admin/**
      resourcePatterns:
        - /media/path/**
        - /
    frontend:
      beanName:
      urlPatterns:
        - /**/frontend/**
        - /**/pc/**
      resourcePatterns:
        - /media/path/**
        - /