server:
  port: 9999
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    ## 参考:https://github.com/drtrang/druid-spring-boot
    ## schema: classpath:import.sql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      async-init: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 30
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: britton
        login-password: britton
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true