spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      #- org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      #- org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  datasource:
    ## 参考:https://github.com/drtrang/druid-spring-boot
    ## schema: classpath:import.sql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      async-init: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 30
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1,localhost
        url-pattern: /druid/*
        login-username: britton
        login-password: britton
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  profiles:
    active: dev
  cache:
    type: none

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.maple.core.datasource.models;cn.maple.modules.*.models
  typeEnumsPackage: cn.maple.core.datasource.model.enums;cn.maple.modules.*.model.enums
  typeHandlersPackage: cn.maple.core.datasource.handler
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-field: is_deleted
      logic-delete-value: id
      logic-not-delete-value: 0
      column-format: "%s"
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: false
    # 如果不配置此项 p6spy不会打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 是否开启MyBatis-Plus的默认插件
maple:
  framework:
    enable:
      sql-illegal: true  # 开启sql性能规范插件
      data-change-recorder: true  # 数据变更记录插件
      data-permission: true  # 开启数据权限处理 需要实现DataPermissionHandler接口
debug: false
