spring:
  cloud:
    nacos:
      discovery:
        namespace: ${NACOS_NAMESPACE:a27b1e7e-a407-4a62-8f25-586f38664853}
        serverAddr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        group: DEFAULT_GROUP
      config:
        namespace: ${NACOS_NAMESPACE:a27b1e7e-a407-4a62-8f25-586f38664853}
        serverAddr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        refresh-enabled: true
        group: DEFAULT_GROUP
        file-extension: yml
  config:
    import: # 需要在项目启动时读取的配置文件
      - optional:nacos:application-${spring.application.name}.yml
      - optional:nacos:redisson.yml
      - optional:nacos:datasource.yml
      - optional:nacos:elasticsearch.yml
      - optional:nacos:rocket-mq.yml
      - optional:nacos:mongodb.yml
      - optional:nacos:app-environment.yml
      - optional:nacos:url-white-lists.yml
      - optional:nacos:seat.yml