server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    remoteip:
      remote-ip-header: X-Real-IP
      protocol-header: X-Forwarded-Proto
  servlet:
    context-path: /gx
  port: 8085
  forward-headers-strategy: framework
  
debug: false
