rabbit:
  publisherConfirmType: SIMPLE
  addresses: 192.168.1.245:5672,192.168.56.101:5672
  username: britton
  password: britton
  publisherReturns: true
  virtualHost: /
  cacheMode: CHANNEL
  default-queue-name: geoxus