customer:
  property1:
    name: jack
  property2:
    age: 18

bot:
  notification:
    exception: > # > 防止语法错误提示
      cn.maple.core.framework.exception.GXDataFormatIncorrectException, # 注意逗号
      cn.maple.core.framework.exception.GXBusinessException