dynamic:
  datasource:
    framework:
      #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #url: jdbc:p6spy:mysql://192.168.56.101:3306/geoxus?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xxxx:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&rewriteBatchedStatements=true
      username: britton
      password: britton
      filters: stat,wall,slf4j
    slave1:
      #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #url: jdbc:p6spy:mysql://192.168.56.101:3306/geoxus?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xx.xx.xx.xx:3306/xx?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
      username: britton
      password: britton
      filters: stat,wall,slf4j