spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
elasticsearch:
  datasource:
    framework:
      uris:
        - 192.168.7.213:9200
      username:
      password:
      primary: true
    secondary:
      uris:
        - 192.168.7.213:9200
      username:
      password:
