rocketmq:
  nameServer: 1.1.1.1:9876
  producer:
    group: groupA
    accessKey: 1111
    secretKey: 11111
  consumer:
    group: groupA
    topic: topicA(optional)
    accessKey: 1111
    secretKey: 1111