server:
  port: 4455

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
  profiles:
    active: dev

enable-caffeine: AB